### PR TITLE
fix: Babel transpiler fixes

### LINKED ISSUE #185: Yarn PNP @babel/plugin-syntax-dynamic-import warning
- Version: 3.0.2
- Rollup Version: 2.75.7
- Operating System and version (if applicable): Does not matter
- Node Version (if applicable): 18.4.0
- Does it work with `tsc` (if applicable): Does not matter

### Question

Using yarn PNP (loose mode) along babel + typescript, I get this warning. Upon further looking into the codebase, I see `@babel/plugin-syntax-dynamic-import` is [explicitly `require`d](https://github.com/wessberg/rollup-plugin-ts/blob/15e8edd828972cad274caab88ac91081414e82c5/src/transpiler/babel.ts#L55), but is not in mentioned in the [peer dependencies](https://github.com/wessberg/rollup-plugin-ts/blob/master/package.json#L116). Shouldn't it be included too?

```
(node:105076) [MODULE_NOT_FOUND] Error: rollup-plugin-ts tried to access @babel/plugin-syntax-dynamic-import, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
    at makeError (D:\Projects\absence\.pnp.cjs:17124:34)
    at resolveToUnqualified (D:\Projects\absence\.pnp.cjs:18038:21)
    at resolveRequest (D:\Projects\absence\.pnp.cjs:18129:31)
    at Object.resolveRequest (D:\Projects\absence\.pnp.cjs:18192:26)
    at Function.require$$0.Module._resolveFilename (D:\Projects\absence\.pnp.cjs:17352:34)
    at resolve (node:internal/modules/cjs/helpers:108:19)
    at getForcedBabelOptions (D:\Projects\absence\.yarn\__virtual__\rollup-plugin-ts-virtual-d3ddc4ca44\4\C:\Users\Sagnik Pradhan\AppData\Local\Yarn\Berry\cache\rollup-plugin-ts-npm-3.0.2-62f6d8bffb-9.zip\node_modules\rollup-plugin-ts\src\transpiler\babel.ts:55:4)
    at Object.options (D:\Projects\absence\.yarn\__virtual__\rollup-plugin-ts-virtual-d3ddc4ca44\4\C:\Users\Sagnik Pradhan\AppData\Local\Yarn\Berry\cache\rollup-plugin-ts-npm-3.0.2-62f6d8bffb-9.zip\node_modules\rollup-plugin-ts\src\plugin\typescript-plugin.ts:270:21)
    at C:\Users\Sagnik Pradhan\AppData\Local\Yarn\Berry\cache\rollup-npm-2.75.7-3918160ee7-9.zip\node_modules\rollup\dist\shared\rollup.js:23716:22
    at getInputOptions (C:\Users\Sagnik Pradhan\AppData\Local\Yarn\Berry\cache\rollup-npm-2.75.7-3918160ee7-9.zip\node_modules\rollup\dist\shared\rollup.js:23709:61)
```
It seems like, under typical scenarios, it's falling back to other dependencies to provide it.

### LINKED ISSUE #189: Implicitly added babel plugins
- Version: 3.0.2
- Rollup Version: 2.77.0
- Operating System and version (if applicable): OSX
- Node Version (if applicable): 16
- Does it work with `tsc` (if applicable): n/a

### Reproduction

* add the plugin with a config like this:

```js
typescript({
  transpiler: 'babel',
  browserslist: false,
  transpileOnly: false,
})
```

* let it compile code that includes for example object spread syntax

### Expected Behavior

I am trying to apply only the explicitly configured babel plugins, and otherwise let the code be "ESLatest".

The [docs say](https://github.com/wessberg/rollup-plugin-ts/blob/84e1b7289f052221e383ec55abc636d7278e20eb/README.md#babelpreset-env-behavior-and-how-to-opt-out):

> If you don't want this behavior, simply pass the browserslist: false option to the plugin. Doing so will never apply @babel/preset-env and not apply any additional syntax transformations

According to this, I am expecting only the explicitly configured babel plugins to be used. Which means the object spread is *not* transpiled away. 

### Actual Behavior

My use of object spread syntax is unnecessarily transpiled away, and [this babel helper function](https://github.com/babel/babel/blob/62fd56ffd1576483128f8f53f17e11286800f370/packages/babel-helpers/src/helpers.ts#L312-L330) is included as a polyfill into the bundle.

### Comment

Amongst others, `@babel/plugin-proposal-object-rest-spread` is added implicitly [here](https://github.com/wessberg/rollup-plugin-ts/blob/15e8edd828972cad274caab88ac91081414e82c5/src/transpiler/babel.ts#L109-L117). I do not understand the rationale behind this logic. Why are these plugins implicitly added? And why specifically these five? Object spread is AFAIK an approved ES2018 feature, supported in all modern browsers and node. So no need for transpilation *by default*, and without a way to disable this behavior.

### PR DESCRIPTION
**Pull request by clemyan**
A few fixes for when using Babel as transpiler.

### ~~Babel and `browserslist: false`~~

~~Remove all Babel transformation plugins when using `browserslist: false` [as documented](https://github.com/wessberg/rollup-plugin-ts/blob/84e1b7289f052221e383ec55abc636d7278e20eb/README.md#babelpreset-env-behavior-and-how-to-opt-out)~~

~~Fixes #189~~

### `@babel/plugin-syntax-dynamic-import` resolution

Resolving `@babel/plugin-syntax-dynamic-import` directly is unsound since it is neither a dependency nor a peer dependency. pnpm is supposed to forbid this but don't know why it didn't. Resolve it from `@babel/present-env`

Fixes #185

### `@babel/*` peers

`@babel/*` packages didn't exist until Babel 7. Remove extraneous `>=6.x` from peer version ranges.

### CODE REVIEW

File: src/transpiler/babel.ts [hunk 1]
```diff
@@ -52,7 +52,7 @@ export function getForcedBabelOptions({cwd}: GetForcedBabelOptionsOptions): Tran
 		sourceType: "module",
 		plugins: [
 			// Needed to make babel understand dynamic imports
-			resolveModule("@babel/plugin-syntax-dynamic-import")
+			resolveModule("@babel/plugin-syntax-dynamic-import", resolveModule("@babel/preset-env"))
```
Comment (simonihmig) [inline src/transpiler/babel.ts:55]: Shouldn't we just declare a dependency on `@babel/plugin-syntax-dynamic-import` and resolve it directly? We are now again assuming some other packages will bring in what we depend on, instead of just declaring our own dependencies properly, right?

**Review by simonihmig — APPROVED** [review]
Left one comment, otherwise this looks good to me! (but I have no authority here 🙃)

This would also fix https://github.com/wessberg/rollup-plugin-ts/issues/215, which I just ran into...

**Comment by simonihmig** [comment]
@wessberg could you please look into this? The issues getting solved by this (three of them!) would become significant blockers for continuing to use this plugin for "us" (Ember.js ecosystem). Thank you! 🙏

File: src/transpiler/babel.ts (hunk 1 above)
Comment (clemyan) [reply src/transpiler/babel.ts:55]: Ideally `@babel/plugin-syntax-dynamic-import` should be added as a peer dependency. I was mainly trying to avoid introducing a breaking change.

Yes it relies on `@babel/preset-env` having a dependency on `@babel/plugin-syntax-dynamic-import`. This change it least removes the reliance on it being hoisted to the top-level under `node_modules`.

Comment (wessberg) [reply src/transpiler/babel.ts:55]: Two things:

1. This particular change will cause `babel/preset-env` to be loaded as a  _forced_ babel option. Also, as far as I'm aware it won't actually work, since presets must be provided to babel via the `presets` property instead. But [as described here](https://github.com/wessberg/rollup-plugin-ts#babelpreset-env-behavior-and-how-to-opt-out), it should be possible to use Babel without `@babel/preset-env` being applied. All we really want here is for Babel to at the very least support dynamic imports, considering it is such a fundamental part of bundling together an application or library, and we'll need Babel to understand that Syntax for Rollup to do its thing.

2. To my knowledge, this won't in any way affect #185, as it will still end up attempting to resolve `@babel/plugin-syntax-dynamic-import` without there being an explicit peer dependency on it.

Historically, the reason why there were no declared dependencies on these babel plugins is that there were a ton of them, and I didn't find the user experience nice at all to ask users to install a gazillion packages themselves just to get started, especially when they're all covered by `@babel/preset-env`.

But now, as we no longer forcefully load the other syntax plugins like object-rest-spread, etc, I think I'm in favor of adding an explicit dependency on `@babel/plugin-syntax-dynamic-import` as a peer dependency and making it a breaking change, as @simonihmig also suggested.

File: src/util/path/path-util.ts [hunk 2]
```diff
@@ -20,7 +20,7 @@ import {ensureArray} from "../ensure-array/ensure-array.js";
 import {createRequire} from "module";
 
 // Until import.meta.resolve becomes stable, we'll have to do this instead
-export const resolveModule = createRequire(import.meta.url).resolve;
+export const resolveModule = (id: string, from: string = import.meta.url) => createRequire(from).resolve(id);
```
Comment (wessberg) [inline src/util/path/path-util.ts:23]: What's the thoughts behind this change?

File: src/transpiler/babel.ts [hunk 3]
```diff
@@ -105,16 +105,6 @@ export function getDefaultBabelOptions({browserslist, transpilerOptions}: GetDef
 				  ])
 		],
 		plugins: [
-			// If preset-env will be included, shipped proposals will be included already. If not, apply them here
```
Comment (wessberg) [inline src/transpiler/babel.ts:108]: All of the changes you've made here has been done by my self in the meantime, including swapping the comments, so to avoid merge conflicts I think these changes should be removed. If you pull in the latest changes from master, I think it will sort itself nicely.

**Review by wessberg — CHANGES_REQUESTED** [review]
Excellent work! I've left a few comments.

File: src/transpiler/babel.ts (hunk 1 above)
Comment (clemyan) [reply src/transpiler/babel.ts:55]: I think you misread. I am not adding `@babel/preset-env` as a plugin, I am passing `resolveModule("@babel/preset-env")` as a second argument to `resolveModule`. This is related to the other change you are asking about.

Currently the dependency tree of a project using `rollup-plugin-ts` looks like this

```
<project>
├ rollup-plugin-ts -- (peer) --> @babel/preset-env
└ @babel/present-env
    └ @babel/plugin-syntax-dynamic-import
```

With a strict resolution strategy like PNP, code inside `rollup-plugin-ts` cannot import `@babel/plugin-syntax-dynamic-import` since it is not a dependency nor a peer dependency. However, `rollup-plugin-ts` can resolve `@babel/preset-env`, and `@babel/preset-env` can resolve `@babel/plugin-syntax-dynamic-import`.

To do this, we need use `createRequire(import.meta.url).resolve('@babel/preset-env')`, which returns the path to a module inside `@babel/preset-env`, then `createRequire(path).resolve` to resolve *on behalf of* `@babel/preset-env`. Thus the changes here and in `path-utils.ts`.

----

But this is all moot if you are open to making this a breaking change.

Comment (wessberg) [reply src/transpiler/babel.ts:55]: Aha, I see. You're right that I misread that. That _does_ seem really smart. While I realize there's a slight risk that `@babel/preset-env` will eventually drop its own dependency on `@babel/plugin-syntax-dynamic-import`, it does feel very unlikely. Given that, let's proceed with the change you've made here. Good job!

Comment (clemyan) [reply src/transpiler/babel.ts:56]: > there's a slight risk that @babel/preset-env will eventually drop its own dependency on @babel/plugin-syntax-dynamic-import

Exactly. I'll proceed with my original changes but I have added a TODO comment to actually add a peer dep on `@babel/plugin-syntax-dynamic-import` if and when preparing the next major.

**Comment by wessberg** [comment]
LGTM. Thanks a lot for your contribution.
